sylius_grid:
    grids:
        setono_sylius_consent_management_admin_widget_config:
            driver:
                options:
                    class: "%setono_sylius_consent_management.model.widget_config.class%"
            fields:
                channel:
                    type: twig
                    label: sylius.ui.channel
                    options:
                        template: "@SyliusAdmin/Order/Grid/Field/channel.html.twig"
                locale:
                    type: twig
                    label: sylius.ui.locale
                    options:
                        template: "@SyliusAdmin/Locale/Grid/Field/name.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update

