setono_sylius_consent_management_admin_consent_entry:
    resource: |
        section: admin
        alias: setono_sylius_consent_management.consent_entry
        templates: "@SyliusAdmin\\Crud"
        permission: true
        only: ['index']
        grid: setono_sylius_consent_management_admin_consent_entry
        vars:
            all:
                header: setono_sylius_consent_management.ui.consent_entry_header
                subheader: setono_sylius_consent_management.ui.consent_entry_subheader
    type: sylius.resource

setono_sylius_consent_management_admin_cookie:
    resource: |
        section: admin
        alias: setono_sylius_consent_management.cookie
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_consent_management_admin_cookie
        vars:
            all:
                header: setono_sylius_consent_management.ui.cookie_header
                subheader: setono_sylius_consent_management.ui.cookie_subheader
                templates:
                    form: "@SetonoSyliusConsentManagementPlugin/admin/cookie/_form.html.twig"
    type: sylius.resource

setono_sylius_consent_management_admin_service:
    resource: |
        section: admin
        alias: setono_sylius_consent_management.service
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_consent_management_admin_service
        vars:
            all:
                header: setono_sylius_consent_management.ui.service_header
                subheader: setono_sylius_consent_management.ui.service_subheader
                templates:
                    form: "@SetonoSyliusConsentManagementPlugin/admin/service/_form.html.twig"
    type: sylius.resource

setono_sylius_consent_management_admin_widget_config:
    resource: |
        section: admin
        alias: setono_sylius_consent_management.widget_config
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        permission: true
        grid: setono_sylius_consent_management_admin_widget_config
        vars:
            all:
                header: setono_sylius_consent_management.ui.widget_config_header
                subheader: setono_sylius_consent_management.ui.widget_config_subheader
                templates:
                    form: "@SetonoSyliusConsentManagementPlugin/admin/widget_config/_form.html.twig"
    type: sylius.resource
