setono_sylius_consent_management_shop_ajax_widget:
    path: /ajax/consent-widget
    methods: GET
    defaults:
        _controller: Setono\SyliusConsentManagementPlugin\Controller\ConsentController::widget
        
setono_sylius_consent_management_shop_partial_widget:
    path: /_partial/consent-widget
    methods: GET
    defaults:
        _controller: Setono\SyliusConsentManagementPlugin\Controller\ConsentController::widget
        
setono_sylius_consent_management_shop_update_consent:
    path: /ajax/update-consent
    methods: POST
    defaults:
        _controller: Setono\SyliusConsentManagementPlugin\Controller\ConsentController::update
