<?php

declare(strict_types=1);

namespace Setono\SyliusConsentManagementPlugin\Factory;

use Setono\SyliusConsentManagementPlugin\Model\CookieInterface;
use Setono\SyliusConsentManagementPlugin\Provider\UrlProvider\Url;
use Sylius\Component\Channel\Context\ChannelContextInterface;
use Sylius\Component\Channel\Context\ChannelNotFoundException;
use Sylius\Resource\Factory\FactoryInterface;
use Symfony\Component\BrowserKit\Cookie as BrowserKitCookie;
use Symfony\Component\HttpFoundation\RequestStack;

final class CookieFactory implements CookieFactoryInterface
{
    /**
     * The length of the url column, see Resources/config/doctrine/model/Cookie.orm.xml
     */
    private const URL_MAX_LENGTH = 255;

    public function __construct(
        private readonly FactoryInterface $decorated,
        private readonly ChannelContextInterface $channelContext,
        private readonly RequestStack $requestStack,
    ) {
    }

    public function createNew(): CookieInterface
    {
        /** @var CookieInterface $obj */
        $obj = $this->decorated->createNew();
        $obj->setUrl($this->resolveUrl());

        try {
            $obj->addChannel($this->channelContext->getChannel());
        } catch (ChannelNotFoundException) {
        }

        return $obj;
    }

    public function createWithName(string $name): CookieInterface
    {
        $obj = $this->createNew();
        $obj->setName($name);

        return $obj;
    }

    public function createFromSample(mixed $sample): CookieInterface
    {
        if (!is_array($sample)) {
            throw new \InvalidArgumentException('The sample must be an array');
        }

        if (!array_key_exists('name', $sample) || !array_key_exists('expires', $sample)) {
            throw new \InvalidArgumentException('The sample must contain the keys "name" and "expires"');
        }

        if (!is_string($sample['name']) || '' === $sample['name']) {
            throw new \InvalidArgumentException('The sample key "name" must be a non-empty string');
        }

        if (null !== $sample['expires'] && !is_numeric($sample['expires'])) {
            throw new \InvalidArgumentException('The sample key "expires" must be null or numeric');
        }

        $cookie = $this->createNew();
        $cookie->setName($sample['name']);

        if (null === $sample['expires']) {
            $cookie->setSession(true);
        } else {
            $cookie->setTtl(self::timestampToInterval((int) ($sample['expires'] / 1000)));
        }

        return $cookie;
    }

    public function createFromBrowserKitCookie(BrowserKitCookie $cookie, Url $url): CookieInterface
    {
        $entity = $this->createNew();
        // Crawled URLs are generated by the plugin and the query string tells which tracking parameter triggered the cookie, so it's kept
        $entity->setUrl(mb_substr((string) $url, 0, self::URL_MAX_LENGTH));
        $entity->setName($cookie->getName());

        if (null !== $url->channel) {
            $entity->addChannel($url->channel);
        }

        $expires = $cookie->getExpiresTime();

        if (null === $expires) {
            $entity->setSession(true);
        } else {
            $entity->setTtl(self::timestampToInterval((int) $expires));
        }

        return $entity;
    }

    private function resolveUrl(): ?string
    {
        $request = $this->requestStack->getMainRequest();
        if (null === $request) {
            return null;
        }

        if (!$request->isXmlHttpRequest()) {
            return self::normalizeRequestUrl($request->getUri());
        }

        // Anyone can post to the sample endpoint with any Referer, and the URL is rendered as a link in the admin.
        // The sampling script always requests the shop itself, so a Referer from another host is ignored
        return self::normalizeRequestUrl($request->headers->get('referer'), $request->getHost());
    }

    /**
     * The URL comes from a visitor's request (or its Referer header), so only http(s) URLs are kept, and the query
     * string and fragment are removed. They may contain the visitor's tracking ids, and they easily make the URL
     * longer than the database column
     */
    private static function normalizeRequestUrl(?string $url, ?string $requiredHost = null): ?string
    {
        if (null === $url) {
            return null;
        }

        $parts = parse_url($url);
        if (false === $parts || !isset($parts['scheme'], $parts['host']) || !in_array(strtolower($parts['scheme']), ['http', 'https'], true)) {
            return null;
        }

        if (null !== $requiredHost && strtolower($parts['host']) !== $requiredHost) {
            return null;
        }

        return mb_substr(sprintf(
            '%s://%s%s%s',
            strtolower($parts['scheme']),
            $parts['host'],
            isset($parts['port']) ? ':' . $parts['port'] : '',
            $parts['path'] ?? '/',
        ), 0, self::URL_MAX_LENGTH);
    }

    private static function timestampToInterval(int $timestamp): \DateInterval
    {
        $now = new \DateTimeImmutable();
        $then = new \DateTimeImmutable('@' . $timestamp);

        return $now->diff($then);
    }
}
