<?php

declare(strict_types=1);

namespace Setono\SyliusConsentManagementPlugin\Checker;

use Symfony\Component\HttpFoundation\Request;

/**
 * Only the consent override and its expiry are signed, not the whole URL. The URLs are generated by the crawler
 * and the scheme or host the application sees can differ from them, e.g. behind a proxy
 */
final class ConsentOverrideSigner implements ConsentOverrideSignerInterface
{
    public const EXPIRES_QUERY_PARAM = '_consent_expires';

    public const SIGNATURE_QUERY_PARAM = '_consent_signature';

    private readonly string $key;

    public function __construct(#[\SensitiveParameter] string $secret)
    {
        if ('' === $secret) {
            throw new \InvalidArgumentException('A non-empty secret is required.');
        }

        // Derive a key of our own, so that other HMAC-SHA256 signers keyed with the same secret, like Symfony's
        // uri_signer, can't be used to forge consent overrides
        $this->key = hash_hmac('sha256', 'setono_sylius_consent_management.consent_override', $secret);
    }

    public function sign(string|array $consent, \DateTimeInterface $expiresAt): array
    {
        $expires = $expiresAt->getTimestamp();

        return [
            RequestBasedConsentChecker::CONSENT_QUERY_PARAM => $consent,
            self::EXPIRES_QUERY_PARAM => $expires,
            self::SIGNATURE_QUERY_PARAM => $this->computeSignature($consent, $expires),
        ];
    }

    public function isSigned(Request $request): bool
    {
        $query = $request->query->all();

        $consent = $query[RequestBasedConsentChecker::CONSENT_QUERY_PARAM] ?? null;
        $expires = $query[self::EXPIRES_QUERY_PARAM] ?? null;
        $signature = $query[self::SIGNATURE_QUERY_PARAM] ?? null;

        if (!(is_string($consent) || is_array($consent)) || !is_string($expires) || 1 !== preg_match('/^\d+$/', $expires) || !is_string($signature)) {
            return false;
        }

        if ((int) $expires < time()) {
            return false;
        }

        return hash_equals($this->computeSignature($consent, (int) $expires), $signature);
    }

    private function computeSignature(string|array $consent, int $expires): string
    {
        return hash_hmac('sha256', http_build_query([
            RequestBasedConsentChecker::CONSENT_QUERY_PARAM => $consent,
            self::EXPIRES_QUERY_PARAM => $expires,
        ], '', '&'), $this->key);
    }
}
