imports:
    - { resource: "@SetonoSyliusConsentManagementPlugin/Resources/config/grids/setono_sylius_consent_management_admin_consent_entry.yaml" }
    - { resource: "@SetonoSyliusConsentManagementPlugin/Resources/config/grids/setono_sylius_consent_management_admin_cookie.yaml" }
    - { resource: "@SetonoSyliusConsentManagementPlugin/Resources/config/grids/setono_sylius_consent_management_admin_service.yaml" }
    - { resource: "@SetonoSyliusConsentManagementPlugin/Resources/config/grids/setono_sylius_consent_management_admin_widget_config.yaml" }

sylius_mailer:
    emails:
        new_cookies:
            subject: setono_sylius_consent_management.emails.new_cookies.subject
            template: "@SetonoSyliusConsentManagementPlugin/email/new_cookies.html.twig"
            
    
sylius_ui:
    events:
        setono_sylius_consent_management.admin.widget_config.index:
            blocks:
                index_header:
                    template: "@SetonoSyliusConsentManagementPlugin/admin/widget_config/index_header.html.twig"
                    priority: 15
